#!/usr/bin/env python3
""" Inserts the current time before each input line """

import sys
import datetime
import argparse

def get_now():
    """Return current time with local timezone"""
    return datetime.datetime.now(datetime.timezone.utc).astimezone()

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    args = parser.parse_args()
    try:
        while True:
            line = sys.stdin.buffer.readline()
            if line == b'':
                break
            now = get_now()
            sys.stdout.buffer.write(now.isoformat().encode('utf8')+b' '+line)
            sys.stdout.buffer.flush()
    except KeyboardInterrupt:
        pass
